// SPDX-License-Identifier: MIT

//! Differential parity: `tests/golden/fusion.csv` holds the output of Fleet's own
//! `fuseState` / `fuseDiscoveredState` (MIT, (c) 2026 Nick Nisi) over an exhaustive input
//! grid, generated by `tools/gen_fusion_golden.mjs`. Flight must agree on state, winning
//! source and timeout flag for every row.

mod support;

use flight_classify::{fuse, Source};
use flight_state::AgentState;
use support::*;

const NOW: u64 = 1_000_000;

fn state(name: &str) -> Option<AgentState> {
    Some(match name {
        "-" => return None,
        "PERMIT" => AgentState::Permit,
        "QUESTION" => AgentState::Question,
        "DONE" => AgentState::Done,
        "BUSY" => AgentState::Busy,
        "IDLE" => AgentState::Idle,
        other => panic!("unknown status {other}"),
    })
}

fn source(name: &str) -> Source {
    match name {
        "hook" => Source::Hook,
        "event" => Source::Event,
        "scrape" => Source::Scrape,
        "default" => Source::Default,
        other => panic!("unknown winner {other}"),
    }
}

fn hooked_row(f: &[&str]) -> String {
    let hook_age: u64 = f[1].parse().unwrap();
    let mut ev = hooked(f[0], NOW - hook_age, NOW);
    if let Some(s) = state(f[2]) {
        let age: u64 = f[3].parse().unwrap();
        ev = with_event(ev, s, NOW - age);
    }
    if let Some(s) = state(f[4]) {
        let rule = if f[5] == "g" {
            "busy.spinner-glyph"
        } else {
            "permit.yn"
        };
        ev = with_screen(ev, s, rule);
    }
    let got = fuse(&ev);
    let want_state = state(f[6]).unwrap();
    let want_timeout = f[8] == "1";
    if (got.state, got.source, got.working_timeout_fired)
        == (want_state, source(f[7]), want_timeout)
    {
        String::new()
    } else {
        format!(
            "{f:?}: got {:?}/{:?}/{}",
            got.state, got.source, got.working_timeout_fired
        )
    }
}

fn discovered_row(f: &[&str]) -> String {
    let mut ev = unhooked(NOW);
    ev.working_glyph = f[1] == "1";
    if let Some(s) = state(f[2]) {
        ev = with_screen(ev, s, "p");
    }
    let got = fuse(&ev).state;
    let want = state(f[3]).unwrap();
    if got == want {
        String::new()
    } else {
        format!("{f:?}: got {got:?}")
    }
}

#[test]
fn flight_agrees_with_fleet_on_every_grid_row() {
    let csv = include_str!("golden/fusion.csv");
    let mut rows = 0;
    let mut mismatches = Vec::new();
    for line in csv.lines().filter(|l| !l.is_empty()) {
        let f: Vec<&str> = line.split(',').collect();
        let bad = if f[0] == "D" {
            discovered_row(&f[..])
        } else {
            hooked_row(&f)
        };
        if !bad.is_empty() {
            mismatches.push(bad);
        }
        rows += 1;
    }
    assert_eq!(rows, 3180, "golden grid changed size");
    assert!(
        mismatches.is_empty(),
        "{} mismatches, first: {:?}",
        mismatches.len(),
        &mismatches[..mismatches.len().min(5)]
    );
}
